### ISSUE TITLE
Maintained? Abandoned

### ISSUE THREAD

**Issue by tm1000** [felixfbecker/php-language-server-protocol#18]
Who maintains this now? Is this abandoned or still worked on @muglug ?

**Comment by zobo** [comment]
Since I continued work on the vscode-php-intellisense and php-language-server code bases, I forked this one too (https://github.com/zobo/php-language-server-protocol).
I was surprised to see psalm is using it.

So if there's anybody looking over this repo, I'd love to contribute.

What do you use it for?

**Comment by tm1000** [comment]
@zobo i use it for psalm (I'm upgrading the LSP in Psalm). @muglug will still accept PRs (I talked to him privately as well)

In my own fork I've updated almost all of this library to support LSP 3.16

@zobo you should fork advanced json RPC as well as there is definitely a bug in there I have not bothered to fix yet

**Comment by zobo** [comment]
Great! I'll definitely have a look. It'd be great if updated code got merged in here and new releases made. I'll make a PR.

**Comment by tm1000** [comment]
@zobo i will push my work to yours just in case. 

But json rpc dispatcher definitely needs to be forked

**Comment by tm1000** [comment]
@zobo I submitted https://github.com/zobo/php-language-server-protocol/pull/1 to your fork. From there we can discuss and submit here. if nothing happens here then use your fork moving forward
